import type { LoaderFunctionArgs } from "react-router";

export const loader = ({ request }: LoaderFunctionArgs) => {
  const url = new URL(request.url);
  const baseUrl = `${url.protocol}//${url.host}`;

  const lines = [
    "User-agent: *",
    "Allow: /",
    "",
    "# Allow AI search assistants and LLM crawlers (GEO — Generative Engine Optimization)",
    "User-agent: GPTBot",
    "Allow: /",
    "",
    "User-agent: OAI-SearchBot",
    "Allow: /",
    "",
    "User-agent: ChatGPT-User",
    "Allow: /",
    "",
    "User-agent: ClaudeBot",
    "Allow: /",
    "",
    "User-agent: Claude-Web",
    "Allow: /",
    "",
    "User-agent: anthropic-ai",
    "Allow: /",
    "",
    "User-agent: Google-Extended",
    "Allow: /",
    "",
    "User-agent: GoogleOther",
    "Allow: /",
    "",
    "User-agent: PerplexityBot",
    "Allow: /",
    "",
    "User-agent: DeepSeekBot",
    "Allow: /",
    "",
    "User-agent: DeepSeek",
    "Allow: /",
    "",
    "User-agent: KimiBot",
    "Allow: /",
    "",
    "User-agent: MoonshotBot",
    "Allow: /",
    "",
    "User-agent: ZhipuAI-Bot",
    "Allow: /",
    "",
    "User-agent: GLM-4",
    "Allow: /",
    "",
    "User-agent: QwenBot",
    "Allow: /",
    "",
    "User-agent: Bytespider",
    "Allow: /",
    "",
    "User-agent: ByteDance",
    "Allow: /",
    "",
    "User-agent: Baiduspider",
    "Allow: /",
    "",
    "User-agent: cohere-ai",
    "Allow: /",
    "",
    "User-agent: MistralBot",
    "Allow: /",
    "",
    "User-agent: YouBot",
    "Allow: /",
    "",
    "User-agent: Amazonbot",
    "Allow: /",
    "",
    "User-agent: meta-externalagent",
    "Allow: /",
    "",
    "User-agent: Meta-ExternalFetcher",
    "Allow: /",
    "",
    "User-agent: Applebot",
    "Allow: /",
    "",
    `Sitemap: ${baseUrl}/sitemap.xml`,
    `# LLM-optimized Markdown summary: ${baseUrl}/llms.txt`,
    `# Full RAG Knowledge Base: ${baseUrl}/llms-full.txt`,
    "",
    "# AI training preference (informational comment only)",
    "# Content-Signal is not a standard robots.txt directive",
  ];

  return new Response(lines.join("\n"), {
    status: 200,
    headers: {
      "Content-Type": "text/plain",
      "Cache-Control": "public, max-age=3600, s-maxage=86400",
    },
  });
};
