name: Auto Deploy weblaud App

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            export NVM_DIR="/home/deployer/.nvm"
            source "$NVM_DIR/nvm.sh"
            cd /var/www/weblaud-site
            ./deploy.sh
